name: cloudnative-platform-image-build

on:
  push:
    branches: [ docker_iac ]

permissions:
  id-token: write
  contents: read

jobs:
  ECR_Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker/frontend/.
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout Terraform branch
        uses: actions/checkout@v2
        with:
          ref: infra-build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform.environment/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform.environment/dev
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform.environment/dev
        run: terraform apply -auto-approve